### ISSUE TITLE
module 'nrarfcn' has no attributes

### ISSUE THREAD

**Issue by ihelshal** [blevic/nrarfcn#23]
module 'nrarfcn' has no attribute 'get_frequency_by_gscn'
module 'nrarfcn' has no attribute 'get_gscn_by_frequency'
module 'nrarfcn' has no attribute 'get_gscn_range'

I used Python 3.9.12 and Successfully installed nrarfcn-2.3.1, all attributes mentioned in Readme are working well except those mentioned above. 

![nrarfcn](https://user-images.githubusercontent.com/44316620/201588965-3b506888-dbdb-4c36-9982-48bb00c046dd.png)

**Comment by blevic** [comment]
Hi @ihelshal, thanks for raising the issue.

I just released nrarfcn version 2.4.0 including those GSCN APIs: https://pypi.org/project/nrarfcn/2.4.0/. Version 2.3.1 didn't have those APIs, as seen [here](https://pypi.org/project/nrarfcn/2.3.1/).

Please update your nrarfcn package to the most recent version. You can use: `pip install nrarfcn==2.4.0` to do so.

**Comment by ihelshal** [comment]
Thanks
