### ISSUE TITLE
How to disable 

### ISSUE THREAD

**Issue by Kjjr7** [blevic/nrarfcn#27]

**Comment by blevic** [comment]
Hello @Kjjr7,

Can you give more details? What's your use case? What do you want to disable?

Thanks

**Comment by Kjjr7** [comment]
I want to disable the EARFCN

**Comment by blevic** [comment]
This package doesn't support EARFCN (LTE/4G), only NRARFCN (NR/5G).

Do you mean disabling the package?

This is a frequency calculator, I'm afraid there is nothing to disable. Please give more details on your setup and your use case for further help.

**Comment by blevic** [comment]
Closing the ticket as not applicable. Please reopen ticket or raise another one with more details if necessary. Thanks!
