### ISSUE TITLE
NR Reference Point A

### ISSUE THREAD

**Issue by houshangazizi** [blevic/nrarfcn#28]
Hi! Is calculation of "NR Reference Point A" covered with this? Thanks!

**Comment by blevic** [comment]
NR Reference Point A may be represented with an NR-ARFCN.
For example if you have `absoluteFrequencyPointA 370092` in SIB1, this corresponds to the following frequency:
```
>>> nr.get_frequency(370092)
1850.46   // MHz
```
In this sense, the frequency corresponding to NR Reference Point A is covered by this module.
